import { Badge, Button, Container, Heading, Input, Select, Text, Textarea, toast } from "@medusajs/ui"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { useEffect, useState } from "react"
import { Link, useNavigate } from "react-router-dom"
import { sdk } from "../../../lib/sdk"

type Block = { type: string; headline?: string; heading?: string; body?: string; image_url?: string; cta_label?: string; cta_url?: string; quote?: string; author?: string; code?: string }
const blankBlock = (type:string):Block => type === "hero" ? { type, headline:"New from MUSE", body:"The latest drop is live.", image_url:"https://musenz.com/images/placeholder.jpg", cta_label:"SHOP NOW", cta_url:"https://musenz.com/store" } : type === "trust" || type === "divider" ? { type } : { type, heading:"A MUSE update", body:"Add campaign copy here." }

export const CampaignForm = ({ id }: { id?: string }) => {
  const navigate=useNavigate(); const queryClient=useQueryClient(); const [name,setName]=useState(""); const [subject,setSubject]=useState(""); const [preview,setPreview]=useState(""); const [utm,setUtm]=useState(""); const [segmentId,setSegmentId]=useState(""); const [blocks,setBlocks]=useState<Block[]>([blankBlock("hero"),blankBlock("trust")]); const [testTo,setTestTo]=useState(""); const [testConfirmation,setTestConfirmation]=useState(""); const [scheduleAt,setScheduleAt]=useState(""); const [scheduleConfirmation,setScheduleConfirmation]=useState("")
  const {data:segments}=useQuery<any>({queryKey:["marketing-segments"],queryFn:()=>sdk.client.fetch("/admin/marketing/segments")})
  const {data:detail}=useQuery<any>({queryKey:["marketing-campaign",id],queryFn:()=>sdk.client.fetch(`/admin/marketing/campaigns/${id}`),enabled:!!id})
  const {data:audiencePreview}=useQuery<any>({queryKey:["marketing-audience-preview",id,scheduleAt],queryFn:()=>sdk.client.fetch(`/admin/marketing/campaigns/${id}/audience-preview?scheduled_at=${encodeURIComponent(new Date(scheduleAt).toISOString())}`),enabled:!!id&&!!scheduleAt})
  useEffect(()=>{if(detail?.campaign){const c=detail.campaign;setName(c.name);setSubject(c.subject);setPreview(c.preview_text);setUtm(c.utm_campaign);setBlocks(c.content?.blocks||[]);const match=(segments?.segments||[]).find((s:any)=>JSON.stringify(s.definition)===JSON.stringify(c.audience_definition));if(match)setSegmentId(match.id)}},[detail,segments])
  const selected=(segments?.segments||[]).find((s:any)=>s.id===segmentId)
  const payload={name,subject,preview_text:preview,utm_campaign:utm,content:blocks,audience_definition:selected?.definition||{operator:"and",rules:[{field:"status",operator:"eq",value:"subscribed"}]}}
  const save=useMutation({mutationFn:()=>sdk.client.fetch<any>(id?`/admin/marketing/campaigns/${id}`:"/admin/marketing/campaigns",{method:"POST",body:payload}),onSuccess:(result)=>{toast.success("Campaign draft saved");queryClient.invalidateQueries({queryKey:["marketing-campaigns"]});if(!id)navigate(`/marketing/campaigns/${result.campaign.id}`)},onError:(e:Error)=>toast.error(e.message)})
  const test=useMutation({mutationFn:()=>sdk.client.fetch(`/admin/marketing/campaigns/${id}/test-send`,{method:"POST",body:{to:testTo,confirmation:testConfirmation}}),onSuccess:()=>{toast.success("Test email sent");queryClient.invalidateQueries({queryKey:["marketing-campaign",id]})},onError:(e:Error)=>toast.error(e.message)})
  const schedule=useMutation({mutationFn:()=>sdk.client.fetch<any>(`/admin/marketing/campaigns/${id}/schedule`,{method:"POST",body:{scheduled_at:new Date(scheduleAt).toISOString(),confirmation:scheduleConfirmation}}),onSuccess:(result)=>{toast.success(`Scheduled for ${result.scheduled_local}`);navigate("/marketing/campaigns")},onError:(e:Error)=>toast.error(e.message)})
  const manage=useMutation({mutationFn:(action:string)=>sdk.client.fetch(`/admin/marketing/campaigns/${id}/manage`,{method:"POST",body:{action}}),onSuccess:()=>queryClient.invalidateQueries({queryKey:["marketing-campaign",id]})})
  const updateBlock=(index:number,key:string,value:string)=>setBlocks(current=>current.map((block,i)=>i===index?{...block,[key]:value}:block))
  const status=detail?.campaign?.status||"draft"
  return <div className="flex flex-col gap-4"><Container><div className="flex items-start justify-between px-6 py-4"><div><div className="flex items-center gap-2"><Heading>{id?name||"Campaign":"Create campaign"}</Heading>{id&&<Badge color={status==="sent"?"green":status==="failed"?"red":"grey"}>{status}</Badge>}</div><Text size="small" className="text-ui-fg-subtle">Safe structured blocks only. Every send includes the MUSE identity and unsubscribe footer.</Text></div><div className="flex gap-2"><Link to="/marketing/campaigns"><Button size="small" variant="secondary">Back</Button></Link>{id&&<Button size="small" variant="secondary" onClick={()=>window.open(`/admin/marketing/campaigns/${id}/preview`,"_blank")}>Preview</Button>}<Button size="small" onClick={()=>save.mutate()} isLoading={save.isPending} disabled={!name||!subject||!preview||!utm}>Save draft</Button></div></div></Container>
    <Container><div className="grid gap-3 p-6 md:grid-cols-2"><label><Text size="xsmall">Campaign name</Text><Input value={name} onChange={(e)=>setName(e.target.value)}/></label><label><Text size="xsmall">UTM campaign</Text><Input value={utm} onChange={(e)=>setUtm(e.target.value.toLowerCase().replace(/[^a-z0-9-_]/g,"-"))}/></label><label><Text size="xsmall">Subject</Text><Input value={subject} onChange={(e)=>setSubject(e.target.value)}/></label><label><Text size="xsmall">Preview text</Text><Input value={preview} onChange={(e)=>setPreview(e.target.value)}/></label><label className="md:col-span-2"><Text size="xsmall">Saved segment</Text><Select value={segmentId} onValueChange={setSegmentId}><Select.Trigger><Select.Value placeholder="All subscribed profiles"/></Select.Trigger><Select.Content>{(segments?.segments||[]).map((segment:any)=><Select.Item key={segment.id} value={segment.id}>{segment.name} · {segment.estimated_count}</Select.Item>)}</Select.Content></Select></label></div></Container>
    <Container><div className="flex flex-col gap-4 p-6"><div className="flex items-center justify-between"><div><Heading level="h2">Structured content</Heading><Text size="small" className="text-ui-fg-subtle">Hero, text, product, category, review, offer, trust and divider blocks.</Text></div><Select onValueChange={(type)=>setBlocks(current=>[...current,blankBlock(type)])}><Select.Trigger className="w-48"><Select.Value placeholder="Add block"/></Select.Trigger><Select.Content>{["hero","text","product_grid","category_row","review","offer","trust","divider"].map(type=><Select.Item key={type} value={type}>{type}</Select.Item>)}</Select.Content></Select></div>{blocks.map((block,index)=><div key={index} className="rounded-lg border p-4"><div className="mb-3 flex items-center justify-between"><Badge>{block.type}</Badge><Button size="small" variant="transparent" onClick={()=>setBlocks(current=>current.filter((_,i)=>i!==index))}>Remove</Button></div>{!["trust","divider"].includes(block.type)&&<div className="grid gap-2 md:grid-cols-2"><Input placeholder={block.type==="hero"?"Headline":"Heading"} value={block.headline||block.heading||""} onChange={(e)=>updateBlock(index,block.type==="hero"?"headline":"heading",e.target.value)}/><Textarea placeholder="Body copy" value={block.body||""} onChange={(e)=>updateBlock(index,"body",e.target.value)}/>{block.type==="hero"&&<><Input placeholder="Image URL" value={block.image_url||""} onChange={(e)=>updateBlock(index,"image_url",e.target.value)}/><Input placeholder="CTA URL" value={block.cta_url||""} onChange={(e)=>updateBlock(index,"cta_url",e.target.value)}/><Input placeholder="CTA label" value={block.cta_label||""} onChange={(e)=>updateBlock(index,"cta_label",e.target.value)}/></>}{block.type==="review"&&<><Input placeholder="Quote" value={block.quote||""} onChange={(e)=>updateBlock(index,"quote",e.target.value)}/><Input placeholder="Author" value={block.author||""} onChange={(e)=>updateBlock(index,"author",e.target.value)}/></>}{block.type==="offer"&&<Input placeholder="Offer code" value={block.code||""} onChange={(e)=>updateBlock(index,"code",e.target.value)}/>}</div>}</div>)}</div></Container>
    {id&&<div className="grid gap-4 lg:grid-cols-2"><Container><div className="flex flex-col gap-3 p-6"><Heading level="h2">Preview and test send</Heading><Text size="small" className="text-ui-fg-subtle">A successful test is required before the audience can be materialised.</Text><Input type="email" placeholder="Test recipient" value={testTo} onChange={(e)=>setTestTo(e.target.value)}/><Input placeholder="Type SEND TEST" value={testConfirmation} onChange={(e)=>setTestConfirmation(e.target.value)}/><Button onClick={()=>test.mutate()} isLoading={test.isPending} disabled={testConfirmation!=="SEND TEST"}>Send test</Button></div></Container><Container><div className="flex flex-col gap-3 p-6"><Heading level="h2">Schedule and confirm</Heading><Text size="small" className="text-ui-fg-subtle">Materialises an immutable audience, applies exclusions and forecasts allowance usage.</Text>{detail?.recipients?.total>0&&<Text size="small">Snapshot: {detail.recipients.eligible} eligible · {detail.recipients.excluded} excluded</Text>}<Input type="datetime-local" value={scheduleAt} onChange={(e)=>setScheduleAt(e.target.value)}/>{audiencePreview&&<div className="rounded-lg border p-3"><Text weight="plus">Pre-send confirmation</Text><Text size="small">{audiencePreview.eligible} recipients · {audiencePreview.excluded} excluded</Text><Text size="small">Projected month: {audiencePreview.projected_month_sends} / {audiencePreview.monthly_safety_limit}</Text><Text size="small">{audiencePreview.scheduled_local} · {audiencePreview.scheduled_utc}</Text><Text size="small">{audiencePreview.subject} · {audiencePreview.sender}</Text><Text size="small">Unsubscribe: valid</Text></div>}<Input placeholder="Type CONFIRM CAMPAIGN" value={scheduleConfirmation} onChange={(e)=>setScheduleConfirmation(e.target.value)}/><Button onClick={()=>schedule.mutate()} isLoading={schedule.isPending} disabled={scheduleConfirmation!=="CONFIRM CAMPAIGN"||!scheduleAt}>Materialise and schedule</Button>{["scheduled","sending"].includes(status)&&<Button variant="secondary" onClick={()=>manage.mutate("pause")}>Pause</Button>}{status==="paused"&&<Button variant="secondary" onClick={()=>manage.mutate("resume")}>Resume</Button>}{!["sent","cancelled"].includes(status)&&<Button variant="danger" onClick={()=>manage.mutate("cancel")}>Cancel campaign</Button>}</div></Container></div>}
  </div>
}
