import { Badge, Button, Container, Heading, Input, Select, Text, Textarea, toast } from "@medusajs/ui"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { useEffect, useState } from "react"
import { Link, useNavigate } from "react-router-dom"
import { sdk } from "../../../lib/sdk"

type Block = { type: string; headline?: string; heading?: string; body?: string; image_url?: string; cta_label?: string; cta_url?: string; quote?: string; author?: string; code?: string; html?: string; filename?: string }
const blankBlock = (type:string):Block => type === "hero" ? { type, headline:"New from MUSE", body:"The latest drop is live.", image_url:"https://musenz.com/images/placeholder.jpg", cta_label:"SHOP NOW", cta_url:"https://musenz.com/store" } : type === "trust" || type === "divider" ? { type } : { type, heading:"A MUSE update", body:"Add campaign copy here." }

export const CampaignForm = ({ id }: { id?: string }) => {
  const navigate=useNavigate(); const queryClient=useQueryClient(); const [name,setName]=useState(""); const [subject,setSubject]=useState(""); const [preview,setPreview]=useState(""); const [utm,setUtm]=useState(""); const [templateKey,setTemplateKey]=useState("raw_html_v1"); const [segmentId,setSegmentId]=useState("all_subscribed"); const [blocks,setBlocks]=useState<Block[]>([]); const [testTo,setTestTo]=useState("")
  const {data:segments}=useQuery<any>({queryKey:["marketing-segments"],queryFn:()=>sdk.client.fetch("/admin/marketing/segments")})
  const {data:subscriberSummary}=useQuery<any>({queryKey:["marketing-subscriber-count"],queryFn:()=>sdk.client.fetch("/admin/marketing/subscribers?status=subscribed&limit=1")})
  const {data:detail}=useQuery<any>({queryKey:["marketing-campaign",id],queryFn:()=>sdk.client.fetch(`/admin/marketing/campaigns/${id}`),enabled:!!id})
  const {data:audiencePreview}=useQuery<any>({queryKey:["marketing-audience-preview",id],queryFn:()=>sdk.client.fetch(`/admin/marketing/campaigns/${id}/audience-preview`),enabled:!!id})
  useEffect(()=>{if(detail?.campaign){const c=detail.campaign;setName(c.name);setSubject(c.subject);setPreview(c.preview_text);setUtm(c.utm_campaign);setTemplateKey(c.template_key||"structured_campaign_v1");setBlocks(c.content?.blocks||[]);const match=(segments?.segments||[]).find((s:any)=>JSON.stringify(s.definition)===JSON.stringify(c.audience_definition));if(match)setSegmentId(match.id)}},[detail,segments])
  const selected=(segments?.segments||[]).find((s:any)=>s.id===segmentId)
  const audienceCount=selected?.estimated_count??subscriberSummary?.count??0
  const payload={name,subject,preview_text:preview,utm_campaign:utm,template_key:templateKey,content:blocks,audience_definition:selected?.definition||{operator:"and",rules:[{field:"status",operator:"eq",value:"subscribed"}]}}
  const save=useMutation({mutationFn:()=>sdk.client.fetch<any>(id?`/admin/marketing/campaigns/${id}`:"/admin/marketing/campaigns",{method:"POST",body:payload}),onSuccess:(result)=>{toast.success("Campaign draft saved");queryClient.invalidateQueries({queryKey:["marketing-campaigns"]});if(!id)navigate(`/marketing/campaigns/${result.campaign.id}`)},onError:(e:Error)=>toast.error(e.message)})
  const test=useMutation({mutationFn:()=>sdk.client.fetch(`/admin/marketing/campaigns/${id}/test-send`,{method:"POST",body:{to:testTo,confirmation:"SEND TEST"}}),onSuccess:()=>{toast.success("Test email sent");queryClient.invalidateQueries({queryKey:["marketing-campaign",id]})},onError:(e:Error)=>toast.error(e.message)})
  const sendNow=useMutation({mutationFn:()=>sdk.client.fetch<any>(`/admin/marketing/campaigns/${id}/schedule`,{method:"POST",body:{scheduled_at:new Date(Date.now()+60_000).toISOString(),confirmation:"CONFIRM CAMPAIGN"}}),onSuccess:()=>{toast.success("Campaign queued to send");navigate("/marketing/campaigns")},onError:(e:Error)=>toast.error(e.message)})
  const manage=useMutation({mutationFn:(action:string)=>sdk.client.fetch(`/admin/marketing/campaigns/${id}/manage`,{method:"POST",body:{action}}),onSuccess:()=>queryClient.invalidateQueries({queryKey:["marketing-campaign",id]})})
  const updateBlock=(index:number,key:string,value:string)=>setBlocks(current=>current.map((block,i)=>i===index?{...block,[key]:value}:block))
  const uploadHtml=async(event:React.ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;if(!file.name.toLowerCase().endsWith(".html")){toast.error("Choose an .html file");return}const html=await file.text();setTemplateKey("raw_html_v1");setBlocks([{type:"html",html,filename:file.name}]);toast.success(`${file.name} loaded`)}
  const status=detail?.campaign?.status||"draft"
  return <div className="flex flex-col gap-4"><Container><div className="flex items-start justify-between px-6 py-4"><div><div className="flex items-center gap-2"><Heading>{id?name||"Campaign":"Create email campaign"}</Heading>{id&&<Badge color={status==="sent"?"green":status==="failed"?"red":"grey"}>{status}</Badge>}</div><Text size="small" className="text-ui-fg-subtle">Choose who receives it, upload the HTML, review a test, then send.</Text></div><div className="flex gap-2"><Link to="/marketing/campaigns"><Button size="small" variant="secondary">Back</Button></Link><Button size="small" onClick={()=>save.mutate()} isLoading={save.isPending} disabled={!name||!subject||!preview||!utm||!blocks.length}>Save and continue</Button></div></div></Container>
    <Container><div className="flex flex-col gap-4 p-6"><div><Text size="xsmall" weight="plus" className="text-ui-fg-subtle">STEP 1</Text><Heading level="h2">Campaign and audience</Heading></div><div className="grid gap-3 md:grid-cols-2"><label><Text size="xsmall">Campaign name</Text><Input value={name} placeholder="Spring Rotation — September 2026" onChange={(e)=>{const next=e.target.value;setName(next);if(!utm)setUtm(next.toLowerCase().replace(/[^a-z0-9-_]/g,"-").replace(/^-|-$/g,""))}}/></label><label><Text size="xsmall">Subject</Text><Input value={subject} placeholder="Spring rotation: nine styles from $140" onChange={(e)=>setSubject(e.target.value)}/></label><label><Text size="xsmall">Preview text</Text><Input value={preview} placeholder="Nine spring styles, with pairs from $140." onChange={(e)=>setPreview(e.target.value)}/></label><label><Text size="xsmall">Audience</Text><Select value={segmentId} onValueChange={setSegmentId}><Select.Trigger><Select.Value/></Select.Trigger><Select.Content><Select.Item value="all_subscribed">All subscribed profiles · {subscriberSummary?.count??"…"}</Select.Item>{(segments?.segments||[]).map((segment:any)=><Select.Item key={segment.id} value={segment.id}>{segment.name} · {segment.estimated_count}</Select.Item>)}</Select.Content></Select><Text size="xsmall" className="mt-1 text-ui-fg-subtle">Only profiles with active marketing consent are eligible. Current estimate: {audienceCount.toLocaleString()}.</Text></label><label><Text size="xsmall">Tracking name</Text><Input value={utm} placeholder="spring-rotation-september-2026" onChange={(e)=>setUtm(e.target.value.toLowerCase().replace(/[^a-z0-9-_]/g,"-"))}/></label><label><Text size="xsmall">Email format</Text><Select value={templateKey} onValueChange={setTemplateKey}><Select.Trigger><Select.Value/></Select.Trigger><Select.Content><Select.Item value="raw_html_v1">Upload an HTML file</Select.Item><Select.Item value="structured_campaign_v1">Build from content blocks</Select.Item><Select.Item value="spring_rotation_launch_v1">Spring Rotation saved template</Select.Item></Select.Content></Select></label></div></div></Container>
    {templateKey==="raw_html_v1"?<Container><div className="flex flex-col gap-3 p-6"><div><Text size="xsmall" weight="plus" className="text-ui-fg-subtle">STEP 2</Text><Heading level="h2">Upload email</Heading><Text size="small" className="text-ui-fg-subtle">Choose one complete .html file. It must use hosted image URLs and contain {"{{unsubscribe_url}}"}.</Text></div><Input type="file" accept=".html,text/html" onChange={uploadHtml}/>{blocks[0]?.type==="html"&&<div className="rounded-lg border p-4"><Text size="small" weight="plus">{blocks[0].filename||"Uploaded HTML"}</Text><Text size="small" className="text-ui-fg-subtle">Ready · {(blocks[0].html||"").length.toLocaleString()} characters</Text></div>}</div></Container>:<Container><div className="flex flex-col gap-4 p-6"><div className="flex items-center justify-between"><div><Heading level="h2">Structured content</Heading><Text size="small" className="text-ui-fg-subtle">Hero, text, product, category, review, offer, trust and divider blocks.</Text></div><Select onValueChange={(type)=>setBlocks(current=>[...current,blankBlock(type)])}><Select.Trigger className="w-48"><Select.Value placeholder="Add block"/></Select.Trigger><Select.Content>{["hero","text","product_grid","category_row","review","offer","trust","divider"].map(type=><Select.Item key={type} value={type}>{type}</Select.Item>)}</Select.Content></Select></div>{blocks.filter(block=>block.type!=="html").map((block,index)=><div key={index} className="rounded-lg border p-4"><div className="mb-3 flex items-center justify-between"><Badge>{block.type}</Badge><Button size="small" variant="transparent" onClick={()=>setBlocks(current=>current.filter((_,i)=>i!==index))}>Remove</Button></div>{!["trust","divider"].includes(block.type)&&<div className="grid gap-2 md:grid-cols-2"><Input placeholder={block.type==="hero"?"Headline":"Heading"} value={block.headline||block.heading||""} onChange={(e)=>updateBlock(index,block.type==="hero"?"headline":"heading",e.target.value)}/><Textarea placeholder="Body copy" value={block.body||""} onChange={(e)=>updateBlock(index,"body",e.target.value)}/>{block.type==="hero"&&<><Input placeholder="Image URL" value={block.image_url||""} onChange={(e)=>updateBlock(index,"image_url",e.target.value)}/><Input placeholder="CTA URL" value={block.cta_url||""} onChange={(e)=>updateBlock(index,"cta_url",e.target.value)}/><Input placeholder="CTA label" value={block.cta_label||""} onChange={(e)=>updateBlock(index,"cta_label",e.target.value)}/></>}{block.type==="review"&&<><Input placeholder="Quote" value={block.quote||""} onChange={(e)=>updateBlock(index,"quote",e.target.value)}/><Input placeholder="Author" value={block.author||""} onChange={(e)=>updateBlock(index,"author",e.target.value)}/></>}{block.type==="offer"&&<Input placeholder="Offer code" value={block.code||""} onChange={(e)=>updateBlock(index,"code",e.target.value)}/>}</div>}</div>)}</div></Container>}
    {id&&<Container><div className="flex flex-col gap-4 p-6"><div><Text size="xsmall" weight="plus" className="text-ui-fg-subtle">STEP 3</Text><Heading level="h2">Review and send</Heading><Text size="small" className="text-ui-fg-subtle">Preview the finished email, send yourself a test, then release it to the selected audience.</Text></div><div className="grid gap-4 lg:grid-cols-2"><div className="flex flex-col gap-3 rounded-lg border p-4"><Heading level="h3">Check the email</Heading><Button variant="secondary" onClick={()=>window.open(`/admin/marketing/campaigns/${id}/preview`,"_blank")}>Open browser preview</Button><Input type="email" placeholder="Your test email address" value={testTo} onChange={(e)=>setTestTo(e.target.value)}/><Button onClick={()=>test.mutate()} isLoading={test.isPending} disabled={!/^\S+@\S+\.\S+$/.test(testTo)}>Send test email</Button>{detail?.campaign?.test_sent_at&&<Text size="small" className="text-ui-fg-subtle">Test sent successfully. This campaign is ready for final confirmation.</Text>}</div><div className="flex flex-col gap-3 rounded-lg border p-4"><Heading level="h3">Send campaign</Heading>{audiencePreview&&<><Text weight="plus">{audiencePreview.eligible.toLocaleString()} eligible recipients</Text><Text size="small" className="text-ui-fg-subtle">{audiencePreview.excluded.toLocaleString()} excluded by consent or frequency rules · {audiencePreview.projected_month_sends.toLocaleString()} / {audiencePreview.monthly_safety_limit.toLocaleString()} projected monthly sends</Text><Text size="small">Subject: {audiencePreview.subject}</Text></>}<Button onClick={()=>{if(window.confirm(`Send “${subject}” to ${audiencePreview?.eligible??audienceCount} eligible subscribers now?`))sendNow.mutate()}} isLoading={sendNow.isPending} disabled={!detail?.campaign?.test_sent_at||!audiencePreview?.eligible}>Send campaign now</Button>{!detail?.campaign?.test_sent_at&&<Text size="small" className="text-ui-fg-subtle">Send a successful test email first.</Text>}{["scheduled","sending"].includes(status)&&<Button variant="secondary" onClick={()=>manage.mutate("pause")}>Pause sending</Button>}{status==="paused"&&<Button variant="secondary" onClick={()=>manage.mutate("resume")}>Resume sending</Button>}</div></div></div></Container>}
  </div>
}
