import { Button, Container, Heading, Input, Select, Table, Text, toast } from "@medusajs/ui"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { useState } from "react"
import { Link } from "react-router-dom"
import { sdk } from "../../../lib/sdk"

const fields = ["status","source_first","primary_preference","customer_type","order_count","lifetime_revenue","signup_days_ago","engaged_days_ago","clicked_within_days","opened_within_days","offer_redeemed"]
const operators = ["eq","neq","gt","gte","lt","lte","true","false"]
const SegmentsPage = () => {
  const queryClient = useQueryClient(); const [name,setName]=useState(""); const [key,setKey]=useState(""); const [field,setField]=useState("status"); const [operator,setOperator]=useState("eq"); const [value,setValue]=useState("subscribed"); const [estimate,setEstimate]=useState<number|null>(null)
  const definition = { operator: "and", rules: [{ field, operator, value: ["true","false"].includes(operator) ? undefined : ["order_count","lifetime_revenue","signup_days_ago","engaged_days_ago","clicked_within_days","opened_within_days"].includes(field) ? Number(value) : value }] }
  const { data } = useQuery<any>({ queryKey:["marketing-segments"], queryFn:()=>sdk.client.fetch("/admin/marketing/segments") })
  const estimateMutation=useMutation({mutationFn:()=>sdk.client.fetch<any>("/admin/marketing/segments/estimate",{method:"POST",body:{definition}}),onSuccess:(result)=>setEstimate(result.estimated_count)})
  const save=useMutation({mutationFn:()=>sdk.client.fetch("/admin/marketing/segments",{method:"POST",body:{name,key,description:null,definition}}),onSuccess:()=>{toast.success("Segment saved");queryClient.invalidateQueries({queryKey:["marketing-segments"]});setName("");setKey("")},onError:(error:Error)=>toast.error(error.message)})
  return <div className="flex flex-col gap-4"><Container><div className="flex items-start justify-between px-6 py-4"><div><Heading>Segments</Heading><Text size="small" className="text-ui-fg-subtle">Saved definitions are evaluated live before a campaign audience is materialised.</Text></div><Link to="/marketing/campaigns"><Button size="small" variant="secondary">Campaigns</Button></Link></div></Container>
    <Container><div className="flex flex-col gap-3 p-6"><Heading level="h2">Build segment</Heading><div className="grid gap-2 md:grid-cols-2"><Input placeholder="Segment name" value={name} onChange={(e)=>{setName(e.target.value);setKey(e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""))}}/><Input placeholder="segment-key" value={key} onChange={(e)=>setKey(e.target.value)}/></div><div className="grid gap-2 md:grid-cols-3"><Select value={field} onValueChange={setField}><Select.Trigger><Select.Value/></Select.Trigger><Select.Content>{fields.map(item=><Select.Item key={item} value={item}>{item}</Select.Item>)}</Select.Content></Select><Select value={operator} onValueChange={setOperator}><Select.Trigger><Select.Value/></Select.Trigger><Select.Content>{operators.map(item=><Select.Item key={item} value={item}>{item}</Select.Item>)}</Select.Content></Select><Input disabled={["true","false"].includes(operator)} value={value} onChange={(e)=>setValue(e.target.value)} /></div><div className="flex items-center gap-2"><Button size="small" variant="secondary" onClick={()=>estimateMutation.mutate()} isLoading={estimateMutation.isPending}>Estimate audience</Button><Button size="small" onClick={()=>save.mutate()} isLoading={save.isPending} disabled={!name||!key}>Save segment</Button>{estimate!==null&&<Text size="small"><strong>{estimate}</strong> eligible profiles</Text>}</div></div></Container>
    <Container><div className="p-6"><Heading level="h2">Saved segments</Heading><Table><Table.Header><Table.Row><Table.HeaderCell>Name</Table.HeaderCell><Table.HeaderCell>Key</Table.HeaderCell><Table.HeaderCell>Estimate</Table.HeaderCell><Table.HeaderCell>Updated</Table.HeaderCell></Table.Row></Table.Header><Table.Body>{(data?.segments||[]).map((segment:any)=><Table.Row key={segment.id}><Table.Cell>{segment.name}<Text size="xsmall" className="text-ui-fg-subtle">{segment.description}</Text></Table.Cell><Table.Cell>{segment.key}</Table.Cell><Table.Cell>{segment.estimated_count}</Table.Cell><Table.Cell>{segment.estimated_at ? new Date(segment.estimated_at).toLocaleString("en-NZ",{timeZone:"Pacific/Auckland"}):"—"}</Table.Cell></Table.Row>)}</Table.Body></Table></div></Container>
  </div>
}
export default SegmentsPage
