import { Badge, Button, Container, Heading, Table, Text } from "@medusajs/ui"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { sdk } from "../../../lib/sdk"

type Event = { id: string; status: string; subject_snapshot: string; scheduled_at: string; template_key: string }
type Enrollment = { id: string; status: string; email_events?: Event[] }
type Step = { id: string; sequence_number: number; name: string; delay_minutes: number; subject: string; preview_text: string; template_key: string }
type Flow = { id: string; name: string; key: string; status: string; version: number; steps: Step[]; enrollments: Enrollment[] }

const AutomationsPage = () => {
  const client = useQueryClient()
  const { data, isLoading, isError } = useQuery<{ flows: Flow[] }>({ queryKey: ["marketing-automations"], queryFn: () => sdk.client.fetch("/admin/marketing/automations") })
  const setup = useMutation({ mutationFn: () => sdk.client.fetch("/admin/marketing/automations", { method: "POST" }), onSuccess: () => client.invalidateQueries({ queryKey: ["marketing-automations"] }) })
  const status = useMutation({ mutationFn: ({ id, status }: { id: string; status: string }) => sdk.client.fetch(`/admin/marketing/automations/${id}`, { method: "POST", body: { status } }), onSuccess: () => client.invalidateQueries({ queryKey: ["marketing-automations"] }) })
  if (isLoading) return <Container><div className="flex justify-center p-8"><Text size="small" className="text-ui-fg-subtle">Loading automations…</Text></div></Container>
  if (isError) return <Container><Text className="text-ui-fg-error">Automations could not be loaded.</Text></Container>
  const flow = data?.flows[0]
  if (!flow) return <Container><div className="flex items-center justify-between px-6 py-4"><div><Heading>Automations</Heading><Text size="small" className="text-ui-fg-subtle">No welcome flow has been configured.</Text></div><Button size="small" isLoading={setup.isPending} onClick={() => setup.mutate()}>Create draft welcome flow</Button></div></Container>
  const events = flow.enrollments.flatMap((item) => item.email_events || [])
  return <div className="flex flex-col gap-3"><Container><div className="flex items-center justify-between px-6 py-4"><div><Heading>{flow.name}</Heading><Text size="small" className="text-ui-fg-subtle">{flow.key} · version {flow.version}</Text></div><Badge color={flow.status === "active" ? "green" : "grey"}>{flow.status}</Badge></div><div className="flex gap-2 px-6 pb-4"><Button size="small" disabled={flow.status === "active" || status.isPending} onClick={() => status.mutate({ id: flow.id, status: "active" })}>Activate locally</Button><Button size="small" variant="secondary" disabled={flow.status !== "active" || status.isPending} onClick={() => status.mutate({ id: flow.id, status: "paused" })}>Pause</Button></div></Container><Container><div className="px-6 py-4"><Text size="small" weight="plus">Flow health</Text><Text size="small" className="text-ui-fg-subtle">{flow.enrollments.length} enrollments · {events.filter((event) => event.status === "scheduled").length} scheduled · {events.filter((event) => event.status === "sent").length} sent</Text></div></Container><Container><div className="px-6 py-4"><Heading level="h2">Five-email timeline</Heading></div><Table><Table.Header><Table.Row><Table.HeaderCell>Step</Table.HeaderCell><Table.HeaderCell>Timing</Table.HeaderCell><Table.HeaderCell>Subject</Table.HeaderCell><Table.HeaderCell>Template</Table.HeaderCell></Table.Row></Table.Header><Table.Body>{[...flow.steps].sort((a,b) => a.sequence_number-b.sequence_number).map((step) => <Table.Row key={step.id}><Table.Cell>{step.sequence_number}. {step.name}</Table.Cell><Table.Cell>{step.delay_minutes === 0 ? "Immediate" : `${step.delay_minutes / 60} hours`}</Table.Cell><Table.Cell>{step.subject}</Table.Cell><Table.Cell>{step.template_key}</Table.Cell></Table.Row>)}</Table.Body></Table></Container><Container><div className="px-6 py-4"><Heading level="h2">Email events</Heading><Text size="small" className="text-ui-fg-subtle">Preview is read-only and cannot send. Test sends require the separate SEND TEST confirmation endpoint.</Text></div><Table><Table.Header><Table.Row><Table.HeaderCell>Subject</Table.HeaderCell><Table.HeaderCell>Status</Table.HeaderCell><Table.HeaderCell>Scheduled</Table.HeaderCell><Table.HeaderCell>Preview</Table.HeaderCell></Table.Row></Table.Header><Table.Body>{events.slice(0, 25).map((event) => <Table.Row key={event.id}><Table.Cell>{event.subject_snapshot}</Table.Cell><Table.Cell><Badge color="grey">{event.status}</Badge></Table.Cell><Table.Cell>{new Date(event.scheduled_at).toLocaleString("en-NZ")}</Table.Cell><Table.Cell><a className="text-ui-fg-interactive hover:underline" href={`/admin/marketing/email-events/${event.id}/preview`} target="_blank" rel="noreferrer">Open preview</a></Table.Cell></Table.Row>)}</Table.Body></Table>{!events.length && <div className="px-6 py-4"><Text size="small" className="text-ui-fg-subtle">No email events yet.</Text></div>}</Container></div>
}
export default AutomationsPage
